# Define a configuração para rodar com imagens do Docker Hub
version: '2'
services:
  rabbit:
    extends:
      file: compose/shared/common.yml
      service: rabbit
  discovery:
    extends:
      file: compose/shared/common.yml
      service: discovery
  gateway:
    extends:
      file: compose/shared/common.yml
      service: gateway
    depends_on:
     - discovery
  services:
    extends:
      file: compose/shared/common.yml
      service: services
    depends_on:
     - rabbit
     - discovery
  ui:
    extends:
      file: compose/shared/common.yml
      service: ui
    depends_on:
     - gateway