# Define a configuração para rodar com imagens locais
version: '2'
services:
  rabbit:
    extends:
      file: compose/shared/common.yml
      service: rabbit
  discovery:
    extends:
      file: compose/shared/common.yml
      service: discovery
    image: stfdigital-plataforma-discovery
  gateway:
    extends:
      file: compose/shared/common.yml
      service: gateway
    image: stfdigital-plataforma-gateway
    depends_on:
     - discovery
  services:
    extends:
      file: compose/shared/common.yml
      service: services
    image: stfdigital-plataforma-services
    depends_on:
     - rabbit
     - discovery
  ui:
    extends:
      file: compose/shared/common.yml
      service: ui
    image: stfdigital-plataforma-ui
    depends_on:
     - gateway