# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  userauthentication:
    extends:
      file: shared/compose/common.yml
      service: userauthentication
    image: stfdigital-plataforma-userauthentication
    depends_on:
     - discovery
