# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  userauthentication:
    extends:
      file: compose/shared/common.yml
      service: userauthentication
    depends_on:
     - discovery