# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  identidades:
    extends:
      file: shared/compose/common.yml
      service: identidades
    image: stfdigital-plataforma-identidades
    depends_on:
     - discovery
