# Extende a configuração para rodar os testes e2e.
# Deve ser rodado em combinação com shared/compose/docker-compose.e2e.base.yml
version: '2'
services:
  identidades:
    extends:
      file: shared/compose/common.yml
      service: identidades
    image: stfdigital-plataforma-identidades
    depends_on:
     - discovery
