Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452180,'Tribunal Superior do Trabalho');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452182,'Tribunal Regional Federal da 1ª Região');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452141,'TRIBUNAL DE JUSTIÇA DO ESTADO DO ESPÍRITO SANTO');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452219,'Tribunal de Justiça do Estado do Amazonas');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452220,'TRIBUNAL DE JUSTIÇA DO ESTADO DO ACRE');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12463563,'Tribunal de Justiça do Estado da Bahia');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12475536,'TRIBUNAL DE JUSTIÇA DO ESTADO DE SÃO PAULO');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12570227,'Tribunal Regional do Trabalho da 23ª Região');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12675529,'Tribunal de Justiça do Estado de Alagoas');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452140,'Tribunal de Justiça do Estado de Goiás');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452896,'Tribunal de Justiça do Estado de Minas Gerais');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452299,'Tribunal de Justiça do Estado do Tocantins');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12473673,'TRF4 - TRIBUNAL REGIONAL FEDERAL DA 4ª REGIAO');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12487766,'Tribunal Regional Federal da 5ª Região');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12930871,'Tribunal de Justiça de Minas Gerais');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452221,'Tribunal de Justiça do Estado do Pernambuco');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12471851,'TRIBUNAL DE JUSTIÇA DO ESTADO DO MATO GROSSO DO SUL');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12486976,'Tribunal de Justiça Militar do Estado de Minas Gerais');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12494482,'TRF2 - Tribunal Regional Federal da 2ª Região');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452298,'Tribunal de Justiça do Estado do Rio de Janeiro');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452222,'Tribunal de Justiça do Estado do Ceará');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12468280,'Tribunal de Justiça do Estado do Pará');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452179,'Tribunal Regional Federal da 4ª Região');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452261,'Superior Tribunal de Justiça');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452262,'Tribunal de Justiça do Estado do Maranhão');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12551363,'Tribunal Regional do Trabalho da 24ª Região');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12701773,'Tribunal de Justiça do Estado de Mato Grosso do Sul');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452662,'Tribunal de Justiça do Estado de Santa Catarina');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12473966,'TRF1 - TRIBUNAL REGIONAL FEDERAL DA 1ª REGIAO');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452260,'Tribunal de Justiça do Estado de Sergipe');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452183,'Tribunal de Justiça do Estado do Paraná');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452898,'Tribunal de Justiça do Estado do Rio Grande do Sul');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12452825,'Tribunal de Justiça do Distrito Federal e Territórios');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12464809,'Tribunal Superior Eleitoral');
Insert into corporativo.orgao (SEQ_PESSOA,NOM_PESSOA) values (12596313,'Tribunal de Justiça do Estado do Amapá');

INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (16, 'Peticionador');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (18, 'Representante');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (26, 'Gestor Recebimento');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (28, 'Gestor Cadastro');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (29, 'Cidadao');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (20, 'Autuador');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (21, 'Distribuidor');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (22, 'Cartoraria');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (23, 'Gestor Autuacao');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (24, 'Usuario Teste');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (25, 'TOMAS GODOI');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (27, 'Gestor Orgao');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (17, 'Recebedor');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (30, 'Preautuador Recursal');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (19, 'Preautuador Originario');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (31, 'Autuador Recursal Ce');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (32, 'Analista Pressupostos');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (33, 'Revisor Processo Ri');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (34, 'Analista Repercussao G');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (35, 'Revisor Repercussao G');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (36, 'Autuador Recursal');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (37, 'Organizador Pecas');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (38, 'Gestor Modelo');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (39, 'Gestor Modelo 01');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (40, 'Gestor Modelo 02');
INSERT INTO corporativo.pessoa(SEQ_PESSOA, NOM_PESSOA) VALUES (41, 'Representante Tribunal');

insert into corporativo.associado (seq_associado, seq_pessoa, tip_associado, dsc_cargo_funcao, seq_pessoa_orgao) values (corporativo.seq_associado.nextval, 18, 'REPRESENTANTE', 'Analista Representante', 12452261);
insert into corporativo.associado (seq_associado, seq_pessoa, tip_associado, dsc_cargo_funcao, seq_pessoa_orgao) values (corporativo.seq_associado.nextval, 27, 'GESTOR', 'Analista Gestor', 12452261);
insert into corporativo.associado (seq_associado, seq_pessoa, tip_associado, dsc_cargo_funcao, seq_pessoa_orgao) values (corporativo.seq_associado.nextval, 41, 'REPRESENTANTE', 'Analista Representante', 12452180);