CREATE SEQUENCE identidades.SEQ_RECURSO START WITH 1 nomaxvalue minvalue 1 nocycle nocache;
CREATE SEQUENCE identidades.SEQ_USUARIO START WITH 27 nomaxvalue minvalue 1 nocycle nocache;
CREATE SEQUENCE identidades.SEQ_TIPO_INFORMACAO START WITH 70 nomaxvalue minvalue 1 nocycle nocache;
CREATE SEQUENCE identidades.SEQ_INFORMACAO START WITH 1 nomaxvalue minvalue 1 nocycle nocache;
CREATE SEQUENCE identidades.SEQ_PAPEL START WITH 1 nomaxvalue minvalue 1 nocycle nocache;
CREATE SEQUENCE identidades.SEQ_GRUPO START WITH 1 nomaxvalue minvalue 1 nocycle nocache;
CREATE SEQUENCE identidades.SEQ_SEGMENTO START WITH 1 nomaxvalue minvalue 1 nocycle nocache;

CREATE TABLE identidades.TIPO_INFORMACAO(
    SEQ_TIPO_INFORMACAO NUMBER NOT NULL,
    NOM_TIPO_INFORMACAO VARCHAR2(100) NOT NULL
); 
ALTER TABLE identidades.TIPO_INFORMACAO ADD CONSTRAINT PK_TIPO_INFORMACAO PRIMARY KEY(SEQ_TIPO_INFORMACAO);         

CREATE TABLE identidades.PAPEL(
    SEQ_PAPEL NUMBER NOT NULL,
    NOM_PAPEL VARCHAR2(100) NOT NULL,
    SEQ_GRUPO NUMBER
);        
ALTER TABLE identidades.PAPEL ADD CONSTRAINT PK_PAPEL PRIMARY KEY(SEQ_PAPEL);       

CREATE TABLE identidades.SEGMENTO(
    SEQ_SEGMENTO NUMBER NOT NULL,
    NOM_SEGMENTO VARCHAR2(100) NOT NULL,
    SEQ_TIPO_INFORMACAO NUMBER NOT NULL
);            
ALTER TABLE identidades.SEGMENTO ADD CONSTRAINT PK_SEGMENTO PRIMARY KEY(SEQ_SEGMENTO);              
               
CREATE TABLE identidades.RECURSO(
    SEQ_RECURSO NUMBER NOT NULL,
    NOM_RECURSO VARCHAR2(50) NOT NULL,
    TIP_RECURSO VARCHAR2(20) NOT NULL
);  
ALTER TABLE identidades.RECURSO ADD CONSTRAINT PK_RECURSO PRIMARY KEY(SEQ_RECURSO); 

CREATE TABLE identidades.GRUPO(
    SEQ_GRUPO NUMBER NOT NULL,
    NOM_GRUPO VARCHAR2(100) NOT NULL,
    TIP_GRUPO VARCHAR2(20) NOT NULL
);         
ALTER TABLE identidades.GRUPO ADD CONSTRAINT PK_GRUPO PRIMARY KEY(SEQ_GRUPO);       

CREATE TABLE identidades.GRUPO_USUARIO(
    SEQ_GRUPO NUMBER NOT NULL,
    SEQ_USUARIO NUMBER NOT NULL
);            
ALTER TABLE identidades.GRUPO_USUARIO ADD CONSTRAINT PK_GRUPO_USUARIO PRIMARY KEY(SEQ_GRUPO, SEQ_USUARIO);          

CREATE TABLE identidades.INFORMACAO(
    SEQ_INFORMACAO NUMBER NOT NULL,
    SEQ_TIPO_INFORMACAO NUMBER NOT NULL,
    SEQ_SEGMENTO NUMBER,
    COD_IDENTIDADE VARCHAR2(30) NOT NULL
);             
ALTER TABLE identidades.INFORMACAO ADD CONSTRAINT PK_INFORMACAO PRIMARY KEY(SEQ_INFORMACAO);        

CREATE TABLE identidades.PAPEL_USUARIO(
    SEQ_PAPEL NUMBER NOT NULL,
    SEQ_USUARIO NUMBER NOT NULL
);            
ALTER TABLE identidades.PAPEL_USUARIO ADD CONSTRAINT PK_PAPEL_USUARIO PRIMARY KEY(SEQ_PAPEL, SEQ_USUARIO);          

CREATE TABLE identidades.USUARIO(
    SEQ_USUARIO NUMBER NOT NULL,
    SIG_USUARIO VARCHAR2(30) NOT NULL,
    SEQ_PESSOA NUMBER NOT NULL,
    NOM_PESSOA VARCHAR2(100) NOT NULL,
    COD_CPF_PESSOA VARCHAR2(11),
    COD_OAB_PESSOA VARCHAR2(20),
    DSC_EMAIL_PESSOA VARCHAR2(30),
    DSC_TELEFONE_PESSOA VARCHAR2(20),
    COD_SETOR_LOTACAO NUMBER
);          
ALTER TABLE identidades.USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(SEQ_USUARIO); 

CREATE TABLE identidades.USUARIO_RECURSO(
    SEQ_USUARIO NUMBER NOT NULL,
    SEQ_RECURSO NUMBER NOT NULL
);        
ALTER TABLE identidades.USUARIO_RECURSO ADD CONSTRAINT PK_USUARIO_RECURSO PRIMARY KEY(SEQ_USUARIO, SEQ_RECURSO);    

CREATE TABLE identidades.GRUPO_RECURSO(
    SEQ_GRUPO NUMBER NOT NULL,
    SEQ_RECURSO NUMBER NOT NULL
);            
ALTER TABLE identidades.GRUPO_RECURSO ADD CONSTRAINT PK_GRUPO_RECURSO PRIMARY KEY(SEQ_GRUPO, SEQ_RECURSO);          

CREATE TABLE identidades.PAPEL_RECURSO(
    SEQ_PAPEL NUMBER NOT NULL,
    SEQ_RECURSO NUMBER NOT NULL
);            
ALTER TABLE identidades.PAPEL_RECURSO ADD CONSTRAINT PK_PAPEL_RECURSO PRIMARY KEY(SEQ_PAPEL, SEQ_RECURSO);          

CREATE TABLE identidades.SETOR(
    COD_SETOR NUMBER NOT NULL,
    NOM_SETOR VARCHAR2(100) NOT NULL,
    SIG_SETOR VARCHAR2(30) NOT NULL
);
ALTER TABLE identidades.SETOR ADD CONSTRAINT PK_SETOR PRIMARY KEY(COD_SETOR);

ALTER TABLE identidades.GRUPO ADD CONSTRAINT CK_GRUP_TIP_GRUPO CHECK(TIP_GRUPO IN('COMISSAO', 'CONFIGURACAO', 'GRUPO_TRABALHO', 'ORGAO_CONVENIADO', 'SETOR', 'TRIBUNAL'));  
ALTER TABLE identidades.RECURSO ADD CONSTRAINT CK_RECU_TIP_RECURSO CHECK(TIP_RECURSO IN('ACAO', 'DASHLET', 'DASHBOARD', 'NOTIFICACAO', 'PESQUISA', 'TAREFA'));              
ALTER TABLE identidades.GRUPO ADD CONSTRAINT UK_GRUP_NOM_GRUPO UNIQUE(NOM_GRUPO, TIP_GRUPO);        
ALTER TABLE identidades.TIPO_INFORMACAO ADD CONSTRAINT UK_TIIN_NOM_TIPO_INFORMACAO UNIQUE(NOM_TIPO_INFORMACAO);     
ALTER TABLE identidades.SEGMENTO ADD CONSTRAINT UK_SEGM_NOM_SEGMENTO UNIQUE(NOM_SEGMENTO, SEQ_TIPO_INFORMACAO);     
ALTER TABLE identidades.USUARIO ADD CONSTRAINT UK_USUA_SIG_USUARIO UNIQUE(SIG_USUARIO);             
ALTER TABLE identidades.RECURSO ADD CONSTRAINT UK_RECU_NOM_RECURSO UNIQUE(NOM_RECURSO, TIP_RECURSO);
ALTER TABLE identidades.PAPEL ADD CONSTRAINT UK_PAPE_NOM_PAPEL UNIQUE(NOM_PAPEL);   
ALTER TABLE identidades.INFORMACAO ADD CONSTRAINT UK_INFO_SEQ_TIPO_INFORMACAO UNIQUE(SEQ_TIPO_INFORMACAO, SEQ_SEGMENTO, COD_IDENTIDADE);            
ALTER TABLE identidades.USUARIO ADD CONSTRAINT FK_SETOR_USUA FOREIGN KEY(COD_SETOR_LOTACAO) REFERENCES identidades.SETOR(COD_SETOR);        
ALTER TABLE identidades.GRUPO_RECURSO ADD CONSTRAINT FK_GRUPO_GRRE FOREIGN KEY(SEQ_GRUPO) REFERENCES identidades.GRUPO(SEQ_GRUPO);           
ALTER TABLE identidades.INFORMACAO ADD CONSTRAINT FK_TIPO_INFORMACAO_INFO FOREIGN KEY(SEQ_TIPO_INFORMACAO) REFERENCES identidades.TIPO_INFORMACAO(SEQ_TIPO_INFORMACAO);      
ALTER TABLE identidades.SEGMENTO ADD CONSTRAINT FK_TIPO_INFORMACAO_SEGM FOREIGN KEY(SEQ_TIPO_INFORMACAO) REFERENCES identidades.TIPO_INFORMACAO(SEQ_TIPO_INFORMACAO);        
ALTER TABLE identidades.PAPEL_USUARIO ADD CONSTRAINT FK_PAPEL_PAUS FOREIGN KEY(SEQ_PAPEL) REFERENCES identidades.PAPEL(SEQ_PAPEL);           
ALTER TABLE identidades.GRUPO_USUARIO ADD CONSTRAINT FK_GRUPO_GRUS FOREIGN KEY(SEQ_GRUPO) REFERENCES identidades.GRUPO(SEQ_GRUPO);           
ALTER TABLE identidades.PAPEL_RECURSO ADD CONSTRAINT FK_PAPEL_PARE FOREIGN KEY(SEQ_PAPEL) REFERENCES identidades.PAPEL(SEQ_PAPEL);           
ALTER TABLE identidades.INFORMACAO ADD CONSTRAINT FK_SEGMENTO_INFO FOREIGN KEY(SEQ_SEGMENTO) REFERENCES identidades.SEGMENTO(SEQ_SEGMENTO);  
ALTER TABLE identidades.PAPEL_USUARIO ADD CONSTRAINT FK_USUARIO_PAUS FOREIGN KEY(SEQ_USUARIO) REFERENCES identidades.USUARIO(SEQ_USUARIO);   
ALTER TABLE identidades.USUARIO_RECURSO ADD CONSTRAINT FK_USUARIO_USRE FOREIGN KEY(SEQ_USUARIO) REFERENCES identidades.USUARIO(SEQ_USUARIO); 
ALTER TABLE identidades.GRUPO_RECURSO ADD CONSTRAINT FK_RECURSO_GRRE FOREIGN KEY(SEQ_RECURSO) REFERENCES identidades.RECURSO(SEQ_RECURSO);   
ALTER TABLE identidades.USUARIO_RECURSO ADD CONSTRAINT FK_RECURSO_USRE FOREIGN KEY(SEQ_RECURSO) REFERENCES identidades.RECURSO(SEQ_RECURSO); 
ALTER TABLE identidades.GRUPO_USUARIO ADD CONSTRAINT FK_USUARIO_GRUS FOREIGN KEY(SEQ_USUARIO) REFERENCES identidades.USUARIO(SEQ_USUARIO);   
ALTER TABLE identidades.PAPEL_RECURSO ADD CONSTRAINT FK_RECURSO_PARE FOREIGN KEY(SEQ_RECURSO) REFERENCES identidades.RECURSO(SEQ_RECURSO);   
ALTER TABLE identidades.SETOR ADD CONSTRAINT UK_SETO_SIG_SETOR UNIQUE(SIG_SETOR);
ALTER TABLE identidades.SETOR ADD CONSTRAINT UK_SETO_NOM_SETOR UNIQUE(NOM_SETOR);